### ISSUE TITLE
Missing Conference - Outing model

### ISSUE THREAD

**Issue by Timekiller11** [CtrlWebInc/laralolz#3]
If no one does it I'll make it later, just wanted to leave a trace here.

I know it's unlikely, but I don't see any valid reason to restrict it. If we just do it like this it allows a more flexible fundation for later on and avoid having to redo everything if we change our minds.

**Comment by dvdpearson** [comment]
I couldn't agree more, but I think this is the next thing @cariboufute will do (as he was mandated to create models). Thanks !

**Comment by cariboufute** [comment]
There, it's done! Of course, there were no reasons to restrict that kind of relations.

Again, this needs to be tested. Will make the tests this week...
